### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by SpartanB312** [SpartanB312/Verificator#3]
We will use socket to verify in the next version.Coming soon this weekend.The next version include server and client two projects.

**Comment by ghost** [comment]
Whats your discord?

**Comment by ThnksCJ** [comment]
> We will use socket to verify in the next version.Coming soon this weekend.The next version include server and client two projects.

when will this be done?

**Comment by XeonLyfe** [comment]
> We will use socket to verify in the next version.Coming soon this weekend.The next version include server and client two projects.

I literally made this but in java and with socket servers lmao
