### ISSUE TITLE
This is so bad.

### ISSUE THREAD

**Issue by Crystallinqq** [SpartanB312/Verificator#4]
I hope nobody actually uses this.

**Comment by smallshen** [comment]
and then?

**Comment by Crystallinqq** [comment]
?

**Comment by killermoxiao02** [comment]
why

**Comment by killermoxiao02** [comment]
> 我希望没有人真正使用它。

Is this easy to crack?

**Comment by Rabbit0w0** [comment]
this is good at least he is disclosing source

**Comment by MOMIN5** [comment]
> this is good at least he is disclosing source

just remove one method and boom your client is "cracked"

**Comment by xxxOMA** [comment]
Pastebin auth can be cracked in 3 seconds
