### ISSUE TITLE
Server?

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [SpartanB312/Verificator#6]
What's the point for the server?

**Comment by XeonLyfe** [comment]
you need it to host the jar :)

**Comment by Tarkan-Zarrouk** [comment]
Lot more understanding after latest commit by Spartan lol

**Comment by ThnksCJ** [comment]
Lol ye

**Comment by ThnksCJ** [comment]
We had to wait nearly a year tho to find out

**Comment by Tarkan-Zarrouk** [comment]
👍
