### ISSUE TITLE
yt tutorial?

### ISSUE THREAD

**Issue by ThnksCJ** [SpartanB312/Verificator#8]
could you make a tutorial on how to do everything?

**Comment by redvx** [comment]
lmao

**Comment by ThnksCJ** [comment]
its confusing as fuck to use lmfao

**Comment by Tarkan-Zarrouk** [comment]
> could you make a tutorial on how to do everything?

Step 1: Take server package. 
Step 2: Build server package
Step 3: Get the server.jar
Step 4: Open CMD go to the directory that the server.jar thingy is at.
Step 5: java.jar server.jar 
Step 5: add hwids 
Step 6: Build Client pacakge
Step 7: add your HWID to server.jar 
step 8: launch loader.jar 
boom

**Comment by Tarkan-Zarrouk** [comment]
> its confusing as fuck to use lmfao

Not rly lol
